import './globals.css'
import Link from "next/link";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav><h1>Cool website company!</h1>
        <div>
          <Link href={'/ssr'}>SSR</Link> <Link href={'/csr'}>CSR</Link> <Link href={'/'}>Static</Link>
</div>
        </nav>
        {children}
        </body>
    </html>
  )
}
