
export const revalidate = 0
// export const metadata = {
//   title: 'Home Page',
//   description: 'Generated by create next app',
// }

const fetchTodos = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos')
  const data =  res.json()
  return data
}

export default async function SSR() {
  const todos = await fetchTodos()
  console.log(typeof(todos))
  return (
    <main>
      <h1>Server Side Generated</h1>
      {todos.map((todo) => (
      <div>
        <p key={todo.id}>{todo.title}</p>
      </div>
      ))}
    </main>
  )
}
